# Generated by Django 4.0.2 on 2022-02-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
